[versions]
kotlin = "2.1.0"
compose-plugin = "1.6.11"
itext = "8.0.5"

[libraries]
itext-kernel = { module = "com.itextpdf:kernel", version.ref = "itext" }
itext-layout = { module = "com.itextpdf:layout", version.ref = "itext" }
itext-forms = { module = "com.itextpdf:forms", version.ref = "itext" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
